name = "cli-clap"

description = "A simple CLI application using clap"
homepage    = "https://github.com/termapps/cli-clap"
license     = "MIT"
repository  = "termapps/cli-clap"

[homebrew]
repository = "termapps/homebrew-tap"
